version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test-production:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-production:
          requires:
            - build
  deploy:
    when:
      equal: [ production, << pipeline.git.branch >> ]      
    jobs:
       - deploy #:
#           requires:
#             - test-production
